### ISSUE TITLE
Absence Report form needs backend editing

### ISSUE THREAD

**Issue by zyplos** [2501CodeLab/Lane-Tech-NEO#7]
Currently does nothing, found at **/absence_report.php**

**Comment by heymrhayes** [comment]
Now working;  I just copied over the existing file, made updates to a couple of includes, and added some of the wrapper stuff.

Data is being written to the db, and the PDF is being successfully generated.

There is one issue with a jQuery call that is failing because jq is not included in the page.   

jq should be included in the header;  very little reason not to.   Browser caching means it won't be downloaded each time, and the browser loads the library very efficiently.   I'll post another issue about that.

**Comment by zyplos** [comment]
Fully updated.
